# Generated by Django 4.0.6 on 2022-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(auto_now=True, verbose_name='Дата рождения'),
        ),
    ]
