# Generated by Django 4.0.6 on 2022-08-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_actor_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
    ]
