# Generated by Django 4.0.6 on 2022-08-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_actor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
